### ISSUE TITLE
Typo in generated bash script

### ISSUE THREAD

**Issue by slavniyteo** [pityka/selfpackage#1]
In function `process_args` [here](https://github.com/pityka/selfpackage/blob/c5e78e9385aa58168e560dbef2f65b0788cf5b08/src/main/scala/selfpackage/package.scala#L113) variable `no_more_snp_opts` is used incorrectly. Symbol `$` is missed at line 124.

**Comment by pityka** [comment]
Thank you very much for reporting. I will correct asap.
